title: Nop 平台
description: Nop Platform 2.0 是基于可逆计算原理从零开始构建的新一代低代码平台，它致力于克服低代码平台无法摆脱穷举法的困境，从理论层面超越组件技术，有效的解决粗粒度软件复用的问题。
keywords:
tagline: 基于可逆计算原理从零开始构建的新一代低代码平台

port: 10101

collections:
  pages:
    output: true
    permalink: /:path/

# Handling Reading
exclude:
  - .asset-cache
  - .sass-cache
  - .vscode
  - node_modules
  - build
  - vendors
  - src
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - Gruntfile.coffee
  - bower.json
  - package.json
  - package-lock.json
  - CNAME
encoding: utf-8

# Plugins
gems:
  - jekyll-assets
  - jekyll-archives
  - jekyll-feed
  - jekyll-contentblocks
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-tagging-related_posts
  - jekyll_version_plugin

# Conversion
markdown: kramdown
highlighter: pygments

# Outputting
permalink: /posts/:title/
timezone: Asia/Shanghai

# YAML frontmatter
defaults:
  # 默认
  - scope:
      path: ""
    values:
      layout: ksio/default
  # 页面
  - scope:
      path: ""
      type: pages
    values:
      layout: ksio/page
  # 文章
  - scope:
      path: ""
      type: posts
    values:
      layout: ksio/post
      css:
        - ksio/pages/post
      js:
        - ksio/initializers/time
        - ksio/initializers/lazyload
      siblings: true



# =====
# Plugin-specific configurations
# =====

# Jekyll Archives
# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
    - year
  layouts:
    category: archive/category
    tag: archive/tag
    year: archive/year
  permalinks:
    category: "/categories/:name/"
    tag: "/tags/:name/"
    year: "/archives/:year/"

# Jekyll Feed
feed:
  path: atom.xml
name: Nop 平台
author:
  name: 欧雷
  email: ourairyu@gmail.com
  uri: https://ourai.ws/
  twitter: fxxkol
github:
  url: https://nop-platform.gitee.io



# =====
# Customized configurations
# =====

ksio:
  meta:
    url: https://nop-platform.gitee.io
  brand:
    text: Nop
    color: "#0871ab"
  copyright:
    owner:
      text: Nop 社区
      url: https://nop-platform.gitee.io
    period:
      start: 2024
    provider: true
  header:
    navs:
      - text: 学习
        children:
          - text: 文章
            url: https://www.zhihu.com/column/reversible-computation
          - text: 视频
            url: https://space.bilibili.com/3493261219990250
      - text: 社区
        children:
          - text: 概览
            url: /community/
          - text: Gitee
            url: https://gitee.com/nop-platform
      - text: English
        url: https://nop-platform.github.io
    navbar:
      placement: right
  footer:
    links:
      - text: 社区
        url: /community/
  social:
    share: true
